/**
 *
 *  ClanInvites.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "ClanInvites.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::neondb;

const std::string ClanInvites::Cols::_id = "\"id\"";
const std::string ClanInvites::Cols::_clan_id = "\"clan_id\"";
const std::string ClanInvites::Cols::_invited_user_id = "\"invited_user_id\"";
const std::string ClanInvites::Cols::_invited_by = "\"invited_by\"";
const std::string ClanInvites::Cols::_status = "\"status\"";
const std::string ClanInvites::Cols::_invited_at = "\"invited_at\"";
const std::string ClanInvites::primaryKeyName = "id";
const bool ClanInvites::hasPrimaryKey = true;
const std::string ClanInvites::tableName = "\"clan_invites\"";

const std::vector<typename ClanInvites::MetaData> ClanInvites::metaData_={
{"id","std::string","character varying",64,0,1,1},
{"clan_id","std::string","character varying",64,0,0,1},
{"invited_user_id","std::string","character varying",64,0,0,1},
{"invited_by","std::string","character varying",64,0,0,1},
{"status","std::string","character varying",20,0,0,0},
{"invited_at","::trantor::Date","timestamp without time zone",0,0,0,0}
};
const std::string &ClanInvites::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
ClanInvites::ClanInvites(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["clan_id"].isNull())
        {
            clanId_=std::make_shared<std::string>(r["clan_id"].as<std::string>());
        }
        if(!r["invited_user_id"].isNull())
        {
            invitedUserId_=std::make_shared<std::string>(r["invited_user_id"].as<std::string>());
        }
        if(!r["invited_by"].isNull())
        {
            invitedBy_=std::make_shared<std::string>(r["invited_by"].as<std::string>());
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<std::string>(r["status"].as<std::string>());
        }
        if(!r["invited_at"].isNull())
        {
            auto timeStr = r["invited_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                invitedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            clanId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            invitedUserId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            invitedBy_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            status_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                invitedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

ClanInvites::ClanInvites(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            clanId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            invitedUserId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            invitedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                invitedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

ClanInvites::ClanInvites(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("clan_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["clan_id"].isNull())
        {
            clanId_=std::make_shared<std::string>(pJson["clan_id"].asString());
        }
    }
    if(pJson.isMember("invited_user_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["invited_user_id"].isNull())
        {
            invitedUserId_=std::make_shared<std::string>(pJson["invited_user_id"].asString());
        }
    }
    if(pJson.isMember("invited_by"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["invited_by"].isNull())
        {
            invitedBy_=std::make_shared<std::string>(pJson["invited_by"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("invited_at"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["invited_at"].isNull())
        {
            auto timeStr = pJson["invited_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                invitedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void ClanInvites::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            clanId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            invitedUserId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            invitedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                invitedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void ClanInvites::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("clan_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["clan_id"].isNull())
        {
            clanId_=std::make_shared<std::string>(pJson["clan_id"].asString());
        }
    }
    if(pJson.isMember("invited_user_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["invited_user_id"].isNull())
        {
            invitedUserId_=std::make_shared<std::string>(pJson["invited_user_id"].asString());
        }
    }
    if(pJson.isMember("invited_by"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["invited_by"].isNull())
        {
            invitedBy_=std::make_shared<std::string>(pJson["invited_by"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("invited_at"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["invited_at"].isNull())
        {
            auto timeStr = pJson["invited_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                invitedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &ClanInvites::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ClanInvites::getId() const noexcept
{
    return id_;
}
void ClanInvites::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void ClanInvites::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename ClanInvites::PrimaryKeyType & ClanInvites::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &ClanInvites::getValueOfClanId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(clanId_)
        return *clanId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ClanInvites::getClanId() const noexcept
{
    return clanId_;
}
void ClanInvites::setClanId(const std::string &pClanId) noexcept
{
    clanId_ = std::make_shared<std::string>(pClanId);
    dirtyFlag_[1] = true;
}
void ClanInvites::setClanId(std::string &&pClanId) noexcept
{
    clanId_ = std::make_shared<std::string>(std::move(pClanId));
    dirtyFlag_[1] = true;
}

const std::string &ClanInvites::getValueOfInvitedUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(invitedUserId_)
        return *invitedUserId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ClanInvites::getInvitedUserId() const noexcept
{
    return invitedUserId_;
}
void ClanInvites::setInvitedUserId(const std::string &pInvitedUserId) noexcept
{
    invitedUserId_ = std::make_shared<std::string>(pInvitedUserId);
    dirtyFlag_[2] = true;
}
void ClanInvites::setInvitedUserId(std::string &&pInvitedUserId) noexcept
{
    invitedUserId_ = std::make_shared<std::string>(std::move(pInvitedUserId));
    dirtyFlag_[2] = true;
}

const std::string &ClanInvites::getValueOfInvitedBy() const noexcept
{
    static const std::string defaultValue = std::string();
    if(invitedBy_)
        return *invitedBy_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ClanInvites::getInvitedBy() const noexcept
{
    return invitedBy_;
}
void ClanInvites::setInvitedBy(const std::string &pInvitedBy) noexcept
{
    invitedBy_ = std::make_shared<std::string>(pInvitedBy);
    dirtyFlag_[3] = true;
}
void ClanInvites::setInvitedBy(std::string &&pInvitedBy) noexcept
{
    invitedBy_ = std::make_shared<std::string>(std::move(pInvitedBy));
    dirtyFlag_[3] = true;
}

const std::string &ClanInvites::getValueOfStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ClanInvites::getStatus() const noexcept
{
    return status_;
}
void ClanInvites::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[4] = true;
}
void ClanInvites::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[4] = true;
}
void ClanInvites::setStatusToNull() noexcept
{
    status_.reset();
    dirtyFlag_[4] = true;
}

const ::trantor::Date &ClanInvites::getValueOfInvitedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(invitedAt_)
        return *invitedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ClanInvites::getInvitedAt() const noexcept
{
    return invitedAt_;
}
void ClanInvites::setInvitedAt(const ::trantor::Date &pInvitedAt) noexcept
{
    invitedAt_ = std::make_shared<::trantor::Date>(pInvitedAt);
    dirtyFlag_[5] = true;
}
void ClanInvites::setInvitedAtToNull() noexcept
{
    invitedAt_.reset();
    dirtyFlag_[5] = true;
}

void ClanInvites::updateId(const uint64_t id)
{
}

const std::vector<std::string> &ClanInvites::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "clan_id",
        "invited_user_id",
        "invited_by",
        "status",
        "invited_at"
    };
    return inCols;
}

void ClanInvites::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getClanId())
        {
            binder << getValueOfClanId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getInvitedUserId())
        {
            binder << getValueOfInvitedUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getInvitedBy())
        {
            binder << getValueOfInvitedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getInvitedAt())
        {
            binder << getValueOfInvitedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> ClanInvites::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void ClanInvites::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getClanId())
        {
            binder << getValueOfClanId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getInvitedUserId())
        {
            binder << getValueOfInvitedUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getInvitedBy())
        {
            binder << getValueOfInvitedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getInvitedAt())
        {
            binder << getValueOfInvitedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value ClanInvites::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getClanId())
    {
        ret["clan_id"]=getValueOfClanId();
    }
    else
    {
        ret["clan_id"]=Json::Value();
    }
    if(getInvitedUserId())
    {
        ret["invited_user_id"]=getValueOfInvitedUserId();
    }
    else
    {
        ret["invited_user_id"]=Json::Value();
    }
    if(getInvitedBy())
    {
        ret["invited_by"]=getValueOfInvitedBy();
    }
    else
    {
        ret["invited_by"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getInvitedAt())
    {
        ret["invited_at"]=getInvitedAt()->toDbStringLocal();
    }
    else
    {
        ret["invited_at"]=Json::Value();
    }
    return ret;
}

std::string ClanInvites::toString() const
{
    return toJson().toStyledString();
}

Json::Value ClanInvites::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getClanId())
            {
                ret[pMasqueradingVector[1]]=getValueOfClanId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getInvitedUserId())
            {
                ret[pMasqueradingVector[2]]=getValueOfInvitedUserId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getInvitedBy())
            {
                ret[pMasqueradingVector[3]]=getValueOfInvitedBy();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[4]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getInvitedAt())
            {
                ret[pMasqueradingVector[5]]=getInvitedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getClanId())
    {
        ret["clan_id"]=getValueOfClanId();
    }
    else
    {
        ret["clan_id"]=Json::Value();
    }
    if(getInvitedUserId())
    {
        ret["invited_user_id"]=getValueOfInvitedUserId();
    }
    else
    {
        ret["invited_user_id"]=Json::Value();
    }
    if(getInvitedBy())
    {
        ret["invited_by"]=getValueOfInvitedBy();
    }
    else
    {
        ret["invited_by"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getInvitedAt())
    {
        ret["invited_at"]=getInvitedAt()->toDbStringLocal();
    }
    else
    {
        ret["invited_at"]=Json::Value();
    }
    return ret;
}

bool ClanInvites::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    else
    {
        err="The id column cannot be null";
        return false;
    }
    if(pJson.isMember("clan_id"))
    {
        if(!validJsonOfField(1, "clan_id", pJson["clan_id"], err, true))
            return false;
    }
    else
    {
        err="The clan_id column cannot be null";
        return false;
    }
    if(pJson.isMember("invited_user_id"))
    {
        if(!validJsonOfField(2, "invited_user_id", pJson["invited_user_id"], err, true))
            return false;
    }
    else
    {
        err="The invited_user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("invited_by"))
    {
        if(!validJsonOfField(3, "invited_by", pJson["invited_by"], err, true))
            return false;
    }
    else
    {
        err="The invited_by column cannot be null";
        return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(4, "status", pJson["status"], err, true))
            return false;
    }
    if(pJson.isMember("invited_at"))
    {
        if(!validJsonOfField(5, "invited_at", pJson["invited_at"], err, true))
            return false;
    }
    return true;
}
bool ClanInvites::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ClanInvites::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("clan_id"))
    {
        if(!validJsonOfField(1, "clan_id", pJson["clan_id"], err, false))
            return false;
    }
    if(pJson.isMember("invited_user_id"))
    {
        if(!validJsonOfField(2, "invited_user_id", pJson["invited_user_id"], err, false))
            return false;
    }
    if(pJson.isMember("invited_by"))
    {
        if(!validJsonOfField(3, "invited_by", pJson["invited_by"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(4, "status", pJson["status"], err, false))
            return false;
    }
    if(pJson.isMember("invited_at"))
    {
        if(!validJsonOfField(5, "invited_at", pJson["invited_at"], err, false))
            return false;
    }
    return true;
}
bool ClanInvites::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ClanInvites::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }

            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }

            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }

            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
