/**
 *
 *  Feedbacks.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Feedbacks.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::equatix;

const std::string Feedbacks::Cols::_id = "\"id\"";
const std::string Feedbacks::Cols::_message = "\"message\"";
const std::string Feedbacks::Cols::_rating = "\"rating\"";
const std::string Feedbacks::primaryKeyName = "id";
const bool Feedbacks::hasPrimaryKey = true;
const std::string Feedbacks::tableName = "\"feedbacks\"";

const std::vector<typename Feedbacks::MetaData> Feedbacks::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"message","std::string","character varying",1000,0,0,0},
{"rating","int32_t","integer",4,0,0,0}
};
const std::string &Feedbacks::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Feedbacks::Feedbacks(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["message"].isNull())
        {
            message_=std::make_shared<std::string>(r["message"].as<std::string>());
        }
        if(!r["rating"].isNull())
        {
            rating_=std::make_shared<int32_t>(r["rating"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            message_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            rating_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Feedbacks::Feedbacks(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            message_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            rating_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

Feedbacks::Feedbacks(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("message"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["message"].isNull())
        {
            message_=std::make_shared<std::string>(pJson["message"].asString());
        }
    }
    if(pJson.isMember("rating"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["rating"].isNull())
        {
            rating_=std::make_shared<int32_t>((int32_t)pJson["rating"].asInt64());
        }
    }
}

void Feedbacks::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            message_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            rating_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

void Feedbacks::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("message"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["message"].isNull())
        {
            message_=std::make_shared<std::string>(pJson["message"].asString());
        }
    }
    if(pJson.isMember("rating"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["rating"].isNull())
        {
            rating_=std::make_shared<int32_t>((int32_t)pJson["rating"].asInt64());
        }
    }
}

const int32_t &Feedbacks::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Feedbacks::getId() const noexcept
{
    return id_;
}
void Feedbacks::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Feedbacks::PrimaryKeyType & Feedbacks::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Feedbacks::getValueOfMessage() const noexcept
{
    static const std::string defaultValue = std::string();
    if(message_)
        return *message_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Feedbacks::getMessage() const noexcept
{
    return message_;
}
void Feedbacks::setMessage(const std::string &pMessage) noexcept
{
    message_ = std::make_shared<std::string>(pMessage);
    dirtyFlag_[1] = true;
}
void Feedbacks::setMessage(std::string &&pMessage) noexcept
{
    message_ = std::make_shared<std::string>(std::move(pMessage));
    dirtyFlag_[1] = true;
}
void Feedbacks::setMessageToNull() noexcept
{
    message_.reset();
    dirtyFlag_[1] = true;
}

const int32_t &Feedbacks::getValueOfRating() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(rating_)
        return *rating_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Feedbacks::getRating() const noexcept
{
    return rating_;
}
void Feedbacks::setRating(const int32_t &pRating) noexcept
{
    rating_ = std::make_shared<int32_t>(pRating);
    dirtyFlag_[2] = true;
}
void Feedbacks::setRatingToNull() noexcept
{
    rating_.reset();
    dirtyFlag_[2] = true;
}

void Feedbacks::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Feedbacks::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "message",
        "rating"
    };
    return inCols;
}

void Feedbacks::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMessage())
        {
            binder << getValueOfMessage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getRating())
        {
            binder << getValueOfRating();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Feedbacks::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void Feedbacks::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMessage())
        {
            binder << getValueOfMessage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getRating())
        {
            binder << getValueOfRating();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Feedbacks::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMessage())
    {
        ret["message"]=getValueOfMessage();
    }
    else
    {
        ret["message"]=Json::Value();
    }
    if(getRating())
    {
        ret["rating"]=getValueOfRating();
    }
    else
    {
        ret["rating"]=Json::Value();
    }
    return ret;
}

std::string Feedbacks::toString() const
{
    return toJson().toStyledString();
}

Json::Value Feedbacks::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getMessage())
            {
                ret[pMasqueradingVector[1]]=getValueOfMessage();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getRating())
            {
                ret[pMasqueradingVector[2]]=getValueOfRating();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMessage())
    {
        ret["message"]=getValueOfMessage();
    }
    else
    {
        ret["message"]=Json::Value();
    }
    if(getRating())
    {
        ret["rating"]=getValueOfRating();
    }
    else
    {
        ret["rating"]=Json::Value();
    }
    return ret;
}

bool Feedbacks::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("message"))
    {
        if(!validJsonOfField(1, "message", pJson["message"], err, true))
            return false;
    }
    if(pJson.isMember("rating"))
    {
        if(!validJsonOfField(2, "rating", pJson["rating"], err, true))
            return false;
    }
    return true;
}
bool Feedbacks::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Feedbacks::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("message"))
    {
        if(!validJsonOfField(1, "message", pJson["message"], err, false))
            return false;
    }
    if(pJson.isMember("rating"))
    {
        if(!validJsonOfField(2, "rating", pJson["rating"], err, false))
            return false;
    }
    return true;
}
bool Feedbacks::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Feedbacks::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 1000)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 1000)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
