/**
 *
 *  GameHistory.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace neondb
{

class GameHistory
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _room_id;
        static const std::string _player1_uid;
        static const std::string _player2_uid;
        static const std::string _winner_uid;
        static const std::string _final_score_p1;
        static const std::string _final_score_p2;
        static const std::string _moves;
        static const std::string _played_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit GameHistory(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit GameHistory(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    GameHistory(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    GameHistory() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int32_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int32_t &pId) noexcept;

    /**  For column room_id  */
    ///Get the value of the column room_id, returns the default value if the column is null
    const std::string &getValueOfRoomId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRoomId() const noexcept;
    ///Set the value of the column room_id
    void setRoomId(const std::string &pRoomId) noexcept;
    void setRoomId(std::string &&pRoomId) noexcept;
    void setRoomIdToNull() noexcept;

    /**  For column player1_uid  */
    ///Get the value of the column player1_uid, returns the default value if the column is null
    const std::string &getValueOfPlayer1Uid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPlayer1Uid() const noexcept;
    ///Set the value of the column player1_uid
    void setPlayer1Uid(const std::string &pPlayer1Uid) noexcept;
    void setPlayer1Uid(std::string &&pPlayer1Uid) noexcept;
    void setPlayer1UidToNull() noexcept;

    /**  For column player2_uid  */
    ///Get the value of the column player2_uid, returns the default value if the column is null
    const std::string &getValueOfPlayer2Uid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPlayer2Uid() const noexcept;
    ///Set the value of the column player2_uid
    void setPlayer2Uid(const std::string &pPlayer2Uid) noexcept;
    void setPlayer2Uid(std::string &&pPlayer2Uid) noexcept;
    void setPlayer2UidToNull() noexcept;

    /**  For column winner_uid  */
    ///Get the value of the column winner_uid, returns the default value if the column is null
    const std::string &getValueOfWinnerUid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getWinnerUid() const noexcept;
    ///Set the value of the column winner_uid
    void setWinnerUid(const std::string &pWinnerUid) noexcept;
    void setWinnerUid(std::string &&pWinnerUid) noexcept;
    void setWinnerUidToNull() noexcept;

    /**  For column final_score_p1  */
    ///Get the value of the column final_score_p1, returns the default value if the column is null
    const int32_t &getValueOfFinalScoreP1() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getFinalScoreP1() const noexcept;
    ///Set the value of the column final_score_p1
    void setFinalScoreP1(const int32_t &pFinalScoreP1) noexcept;
    void setFinalScoreP1ToNull() noexcept;

    /**  For column final_score_p2  */
    ///Get the value of the column final_score_p2, returns the default value if the column is null
    const int32_t &getValueOfFinalScoreP2() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getFinalScoreP2() const noexcept;
    ///Set the value of the column final_score_p2
    void setFinalScoreP2(const int32_t &pFinalScoreP2) noexcept;
    void setFinalScoreP2ToNull() noexcept;

    /**  For column moves  */
    ///Get the value of the column moves, returns the default value if the column is null
    const std::string &getValueOfMoves() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMoves() const noexcept;
    ///Set the value of the column moves
    void setMoves(const std::string &pMoves) noexcept;
    void setMoves(std::string &&pMoves) noexcept;
    void setMovesToNull() noexcept;

    /**  For column played_at  */
    ///Get the value of the column played_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfPlayedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getPlayedAt() const noexcept;
    ///Set the value of the column played_at
    void setPlayedAt(const ::trantor::Date &pPlayedAt) noexcept;
    void setPlayedAtToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 9;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<GameHistory>;
    friend drogon::orm::BaseBuilder<GameHistory, true, true>;
    friend drogon::orm::BaseBuilder<GameHistory, true, false>;
    friend drogon::orm::BaseBuilder<GameHistory, false, true>;
    friend drogon::orm::BaseBuilder<GameHistory, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<GameHistory>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<std::string> roomId_;
    std::shared_ptr<std::string> player1Uid_;
    std::shared_ptr<std::string> player2Uid_;
    std::shared_ptr<std::string> winnerUid_;
    std::shared_ptr<int32_t> finalScoreP1_;
    std::shared_ptr<int32_t> finalScoreP2_;
    std::shared_ptr<std::string> moves_;
    std::shared_ptr<::trantor::Date> playedAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[9]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "room_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "player1_uid,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "player2_uid,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "winner_uid,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "final_score_p1,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "final_score_p2,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "moves,";
            ++parametersCount;
        }
        sql += "played_at,";
        ++parametersCount;
        if(!dirtyFlag_[8])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace neondb
} // namespace drogon_model
