/**
 *
 *  GameHistory.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "GameHistory.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::neondb;

const std::string GameHistory::Cols::_room_id = "\"room_id\"";
const std::string GameHistory::Cols::_player1_uid = "\"player1_uid\"";
const std::string GameHistory::Cols::_player2_uid = "\"player2_uid\"";
const std::string GameHistory::Cols::_winner_uid = "\"winner_uid\"";
const std::string GameHistory::Cols::_final_score_p1 = "\"final_score_p1\"";
const std::string GameHistory::Cols::_final_score_p2 = "\"final_score_p2\"";
const std::string GameHistory::Cols::_moves = "\"moves\"";
const std::string GameHistory::Cols::_played_at = "\"played_at\"";
const std::string GameHistory::primaryKeyName = "room_id";
const bool GameHistory::hasPrimaryKey = true;
const std::string GameHistory::tableName = "\"game_history\"";

const std::vector<typename GameHistory::MetaData> GameHistory::metaData_={
{"room_id","std::string","character varying",255,0,1,1},
{"player1_uid","std::string","character varying",255,0,0,0},
{"player2_uid","std::string","character varying",255,0,0,0},
{"winner_uid","std::string","character varying",255,0,0,0},
{"final_score_p1","int32_t","integer",4,0,0,0},
{"final_score_p2","int32_t","integer",4,0,0,0},
{"moves","std::string","jsonb",0,0,0,0},
{"played_at","::trantor::Date","timestamp without time zone",0,0,0,0}
};
const std::string &GameHistory::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
GameHistory::GameHistory(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["room_id"].isNull())
        {
            roomId_=std::make_shared<std::string>(r["room_id"].as<std::string>());
        }
        if(!r["player1_uid"].isNull())
        {
            player1Uid_=std::make_shared<std::string>(r["player1_uid"].as<std::string>());
        }
        if(!r["player2_uid"].isNull())
        {
            player2Uid_=std::make_shared<std::string>(r["player2_uid"].as<std::string>());
        }
        if(!r["winner_uid"].isNull())
        {
            winnerUid_=std::make_shared<std::string>(r["winner_uid"].as<std::string>());
        }
        if(!r["final_score_p1"].isNull())
        {
            finalScoreP1_=std::make_shared<int32_t>(r["final_score_p1"].as<int32_t>());
        }
        if(!r["final_score_p2"].isNull())
        {
            finalScoreP2_=std::make_shared<int32_t>(r["final_score_p2"].as<int32_t>());
        }
        if(!r["moves"].isNull())
        {
            moves_=std::make_shared<std::string>(r["moves"].as<std::string>());
        }
        if(!r["played_at"].isNull())
        {
            auto timeStr = r["played_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                playedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            roomId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            player1Uid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            player2Uid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            winnerUid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            finalScoreP1_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            finalScoreP2_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            moves_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                playedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

GameHistory::GameHistory(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            roomId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            player1Uid_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            player2Uid_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            winnerUid_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            finalScoreP1_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            finalScoreP2_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            moves_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                playedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

GameHistory::GameHistory(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("room_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["room_id"].isNull())
        {
            roomId_=std::make_shared<std::string>(pJson["room_id"].asString());
        }
    }
    if(pJson.isMember("player1_uid"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["player1_uid"].isNull())
        {
            player1Uid_=std::make_shared<std::string>(pJson["player1_uid"].asString());
        }
    }
    if(pJson.isMember("player2_uid"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["player2_uid"].isNull())
        {
            player2Uid_=std::make_shared<std::string>(pJson["player2_uid"].asString());
        }
    }
    if(pJson.isMember("winner_uid"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["winner_uid"].isNull())
        {
            winnerUid_=std::make_shared<std::string>(pJson["winner_uid"].asString());
        }
    }
    if(pJson.isMember("final_score_p1"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["final_score_p1"].isNull())
        {
            finalScoreP1_=std::make_shared<int32_t>((int32_t)pJson["final_score_p1"].asInt64());
        }
    }
    if(pJson.isMember("final_score_p2"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["final_score_p2"].isNull())
        {
            finalScoreP2_=std::make_shared<int32_t>((int32_t)pJson["final_score_p2"].asInt64());
        }
    }
    if(pJson.isMember("moves"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["moves"].isNull())
        {
            moves_=std::make_shared<std::string>(pJson["moves"].asString());
        }
    }
    if(pJson.isMember("played_at"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["played_at"].isNull())
        {
            auto timeStr = pJson["played_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                playedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void GameHistory::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            roomId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            player1Uid_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            player2Uid_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            winnerUid_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            finalScoreP1_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            finalScoreP2_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            moves_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                playedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void GameHistory::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("room_id"))
    {
        if(!pJson["room_id"].isNull())
        {
            roomId_=std::make_shared<std::string>(pJson["room_id"].asString());
        }
    }
    if(pJson.isMember("player1_uid"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["player1_uid"].isNull())
        {
            player1Uid_=std::make_shared<std::string>(pJson["player1_uid"].asString());
        }
    }
    if(pJson.isMember("player2_uid"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["player2_uid"].isNull())
        {
            player2Uid_=std::make_shared<std::string>(pJson["player2_uid"].asString());
        }
    }
    if(pJson.isMember("winner_uid"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["winner_uid"].isNull())
        {
            winnerUid_=std::make_shared<std::string>(pJson["winner_uid"].asString());
        }
    }
    if(pJson.isMember("final_score_p1"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["final_score_p1"].isNull())
        {
            finalScoreP1_=std::make_shared<int32_t>((int32_t)pJson["final_score_p1"].asInt64());
        }
    }
    if(pJson.isMember("final_score_p2"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["final_score_p2"].isNull())
        {
            finalScoreP2_=std::make_shared<int32_t>((int32_t)pJson["final_score_p2"].asInt64());
        }
    }
    if(pJson.isMember("moves"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["moves"].isNull())
        {
            moves_=std::make_shared<std::string>(pJson["moves"].asString());
        }
    }
    if(pJson.isMember("played_at"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["played_at"].isNull())
        {
            auto timeStr = pJson["played_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                playedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &GameHistory::getValueOfRoomId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(roomId_)
        return *roomId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &GameHistory::getRoomId() const noexcept
{
    return roomId_;
}
void GameHistory::setRoomId(const std::string &pRoomId) noexcept
{
    roomId_ = std::make_shared<std::string>(pRoomId);
    dirtyFlag_[0] = true;
}
void GameHistory::setRoomId(std::string &&pRoomId) noexcept
{
    roomId_ = std::make_shared<std::string>(std::move(pRoomId));
    dirtyFlag_[0] = true;
}
const typename GameHistory::PrimaryKeyType & GameHistory::getPrimaryKey() const
{
    assert(roomId_);
    return *roomId_;
}

const std::string &GameHistory::getValueOfPlayer1Uid() const noexcept
{
    static const std::string defaultValue = std::string();
    if(player1Uid_)
        return *player1Uid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &GameHistory::getPlayer1Uid() const noexcept
{
    return player1Uid_;
}
void GameHistory::setPlayer1Uid(const std::string &pPlayer1Uid) noexcept
{
    player1Uid_ = std::make_shared<std::string>(pPlayer1Uid);
    dirtyFlag_[1] = true;
}
void GameHistory::setPlayer1Uid(std::string &&pPlayer1Uid) noexcept
{
    player1Uid_ = std::make_shared<std::string>(std::move(pPlayer1Uid));
    dirtyFlag_[1] = true;
}
void GameHistory::setPlayer1UidToNull() noexcept
{
    player1Uid_.reset();
    dirtyFlag_[1] = true;
}

const std::string &GameHistory::getValueOfPlayer2Uid() const noexcept
{
    static const std::string defaultValue = std::string();
    if(player2Uid_)
        return *player2Uid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &GameHistory::getPlayer2Uid() const noexcept
{
    return player2Uid_;
}
void GameHistory::setPlayer2Uid(const std::string &pPlayer2Uid) noexcept
{
    player2Uid_ = std::make_shared<std::string>(pPlayer2Uid);
    dirtyFlag_[2] = true;
}
void GameHistory::setPlayer2Uid(std::string &&pPlayer2Uid) noexcept
{
    player2Uid_ = std::make_shared<std::string>(std::move(pPlayer2Uid));
    dirtyFlag_[2] = true;
}
void GameHistory::setPlayer2UidToNull() noexcept
{
    player2Uid_.reset();
    dirtyFlag_[2] = true;
}

const std::string &GameHistory::getValueOfWinnerUid() const noexcept
{
    static const std::string defaultValue = std::string();
    if(winnerUid_)
        return *winnerUid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &GameHistory::getWinnerUid() const noexcept
{
    return winnerUid_;
}
void GameHistory::setWinnerUid(const std::string &pWinnerUid) noexcept
{
    winnerUid_ = std::make_shared<std::string>(pWinnerUid);
    dirtyFlag_[3] = true;
}
void GameHistory::setWinnerUid(std::string &&pWinnerUid) noexcept
{
    winnerUid_ = std::make_shared<std::string>(std::move(pWinnerUid));
    dirtyFlag_[3] = true;
}
void GameHistory::setWinnerUidToNull() noexcept
{
    winnerUid_.reset();
    dirtyFlag_[3] = true;
}

const int32_t &GameHistory::getValueOfFinalScoreP1() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(finalScoreP1_)
        return *finalScoreP1_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &GameHistory::getFinalScoreP1() const noexcept
{
    return finalScoreP1_;
}
void GameHistory::setFinalScoreP1(const int32_t &pFinalScoreP1) noexcept
{
    finalScoreP1_ = std::make_shared<int32_t>(pFinalScoreP1);
    dirtyFlag_[4] = true;
}
void GameHistory::setFinalScoreP1ToNull() noexcept
{
    finalScoreP1_.reset();
    dirtyFlag_[4] = true;
}

const int32_t &GameHistory::getValueOfFinalScoreP2() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(finalScoreP2_)
        return *finalScoreP2_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &GameHistory::getFinalScoreP2() const noexcept
{
    return finalScoreP2_;
}
void GameHistory::setFinalScoreP2(const int32_t &pFinalScoreP2) noexcept
{
    finalScoreP2_ = std::make_shared<int32_t>(pFinalScoreP2);
    dirtyFlag_[5] = true;
}
void GameHistory::setFinalScoreP2ToNull() noexcept
{
    finalScoreP2_.reset();
    dirtyFlag_[5] = true;
}

const std::string &GameHistory::getValueOfMoves() const noexcept
{
    static const std::string defaultValue = std::string();
    if(moves_)
        return *moves_;
    return defaultValue;
}
const std::shared_ptr<std::string> &GameHistory::getMoves() const noexcept
{
    return moves_;
}
void GameHistory::setMoves(const std::string &pMoves) noexcept
{
    moves_ = std::make_shared<std::string>(pMoves);
    dirtyFlag_[6] = true;
}
void GameHistory::setMoves(std::string &&pMoves) noexcept
{
    moves_ = std::make_shared<std::string>(std::move(pMoves));
    dirtyFlag_[6] = true;
}
void GameHistory::setMovesToNull() noexcept
{
    moves_.reset();
    dirtyFlag_[6] = true;
}

const ::trantor::Date &GameHistory::getValueOfPlayedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(playedAt_)
        return *playedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &GameHistory::getPlayedAt() const noexcept
{
    return playedAt_;
}
void GameHistory::setPlayedAt(const ::trantor::Date &pPlayedAt) noexcept
{
    playedAt_ = std::make_shared<::trantor::Date>(pPlayedAt);
    dirtyFlag_[7] = true;
}
void GameHistory::setPlayedAtToNull() noexcept
{
    playedAt_.reset();
    dirtyFlag_[7] = true;
}

void GameHistory::updateId(const uint64_t id)
{
}

const std::vector<std::string> &GameHistory::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "room_id",
        "player1_uid",
        "player2_uid",
        "winner_uid",
        "final_score_p1",
        "final_score_p2",
        "moves",
        "played_at"
    };
    return inCols;
}

void GameHistory::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getRoomId())
        {
            binder << getValueOfRoomId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getPlayer1Uid())
        {
            binder << getValueOfPlayer1Uid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPlayer2Uid())
        {
            binder << getValueOfPlayer2Uid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getWinnerUid())
        {
            binder << getValueOfWinnerUid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getFinalScoreP1())
        {
            binder << getValueOfFinalScoreP1();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getFinalScoreP2())
        {
            binder << getValueOfFinalScoreP2();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMoves())
        {
            binder << getValueOfMoves();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getPlayedAt())
        {
            binder << getValueOfPlayedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> GameHistory::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void GameHistory::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getRoomId())
        {
            binder << getValueOfRoomId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getPlayer1Uid())
        {
            binder << getValueOfPlayer1Uid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPlayer2Uid())
        {
            binder << getValueOfPlayer2Uid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getWinnerUid())
        {
            binder << getValueOfWinnerUid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getFinalScoreP1())
        {
            binder << getValueOfFinalScoreP1();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getFinalScoreP2())
        {
            binder << getValueOfFinalScoreP2();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMoves())
        {
            binder << getValueOfMoves();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getPlayedAt())
        {
            binder << getValueOfPlayedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value GameHistory::toJson() const
{
    Json::Value ret;
    if(getRoomId())
    {
        ret["room_id"]=getValueOfRoomId();
    }
    else
    {
        ret["room_id"]=Json::Value();
    }
    if(getPlayer1Uid())
    {
        ret["player1_uid"]=getValueOfPlayer1Uid();
    }
    else
    {
        ret["player1_uid"]=Json::Value();
    }
    if(getPlayer2Uid())
    {
        ret["player2_uid"]=getValueOfPlayer2Uid();
    }
    else
    {
        ret["player2_uid"]=Json::Value();
    }
    if(getWinnerUid())
    {
        ret["winner_uid"]=getValueOfWinnerUid();
    }
    else
    {
        ret["winner_uid"]=Json::Value();
    }
    if(getFinalScoreP1())
    {
        ret["final_score_p1"]=getValueOfFinalScoreP1();
    }
    else
    {
        ret["final_score_p1"]=Json::Value();
    }
    if(getFinalScoreP2())
    {
        ret["final_score_p2"]=getValueOfFinalScoreP2();
    }
    else
    {
        ret["final_score_p2"]=Json::Value();
    }
    if(getMoves())
    {
        ret["moves"]=getValueOfMoves();
    }
    else
    {
        ret["moves"]=Json::Value();
    }
    if(getPlayedAt())
    {
        ret["played_at"]=getPlayedAt()->toDbStringLocal();
    }
    else
    {
        ret["played_at"]=Json::Value();
    }
    return ret;
}

std::string GameHistory::toString() const
{
    return toJson().toStyledString();
}

Json::Value GameHistory::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getRoomId())
            {
                ret[pMasqueradingVector[0]]=getValueOfRoomId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getPlayer1Uid())
            {
                ret[pMasqueradingVector[1]]=getValueOfPlayer1Uid();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPlayer2Uid())
            {
                ret[pMasqueradingVector[2]]=getValueOfPlayer2Uid();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getWinnerUid())
            {
                ret[pMasqueradingVector[3]]=getValueOfWinnerUid();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getFinalScoreP1())
            {
                ret[pMasqueradingVector[4]]=getValueOfFinalScoreP1();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getFinalScoreP2())
            {
                ret[pMasqueradingVector[5]]=getValueOfFinalScoreP2();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getMoves())
            {
                ret[pMasqueradingVector[6]]=getValueOfMoves();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getPlayedAt())
            {
                ret[pMasqueradingVector[7]]=getPlayedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getRoomId())
    {
        ret["room_id"]=getValueOfRoomId();
    }
    else
    {
        ret["room_id"]=Json::Value();
    }
    if(getPlayer1Uid())
    {
        ret["player1_uid"]=getValueOfPlayer1Uid();
    }
    else
    {
        ret["player1_uid"]=Json::Value();
    }
    if(getPlayer2Uid())
    {
        ret["player2_uid"]=getValueOfPlayer2Uid();
    }
    else
    {
        ret["player2_uid"]=Json::Value();
    }
    if(getWinnerUid())
    {
        ret["winner_uid"]=getValueOfWinnerUid();
    }
    else
    {
        ret["winner_uid"]=Json::Value();
    }
    if(getFinalScoreP1())
    {
        ret["final_score_p1"]=getValueOfFinalScoreP1();
    }
    else
    {
        ret["final_score_p1"]=Json::Value();
    }
    if(getFinalScoreP2())
    {
        ret["final_score_p2"]=getValueOfFinalScoreP2();
    }
    else
    {
        ret["final_score_p2"]=Json::Value();
    }
    if(getMoves())
    {
        ret["moves"]=getValueOfMoves();
    }
    else
    {
        ret["moves"]=Json::Value();
    }
    if(getPlayedAt())
    {
        ret["played_at"]=getPlayedAt()->toDbStringLocal();
    }
    else
    {
        ret["played_at"]=Json::Value();
    }
    return ret;
}

bool GameHistory::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("room_id"))
    {
        if(!validJsonOfField(0, "room_id", pJson["room_id"], err, true))
            return false;
    }
    else
    {
        err="The room_id column cannot be null";
        return false;
    }
    if(pJson.isMember("player1_uid"))
    {
        if(!validJsonOfField(1, "player1_uid", pJson["player1_uid"], err, true))
            return false;
    }
    if(pJson.isMember("player2_uid"))
    {
        if(!validJsonOfField(2, "player2_uid", pJson["player2_uid"], err, true))
            return false;
    }
    if(pJson.isMember("winner_uid"))
    {
        if(!validJsonOfField(3, "winner_uid", pJson["winner_uid"], err, true))
            return false;
    }
    if(pJson.isMember("final_score_p1"))
    {
        if(!validJsonOfField(4, "final_score_p1", pJson["final_score_p1"], err, true))
            return false;
    }
    if(pJson.isMember("final_score_p2"))
    {
        if(!validJsonOfField(5, "final_score_p2", pJson["final_score_p2"], err, true))
            return false;
    }
    if(pJson.isMember("moves"))
    {
        if(!validJsonOfField(6, "moves", pJson["moves"], err, true))
            return false;
    }
    if(pJson.isMember("played_at"))
    {
        if(!validJsonOfField(7, "played_at", pJson["played_at"], err, true))
            return false;
    }
    return true;
}
bool GameHistory::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool GameHistory::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("room_id"))
    {
        if(!validJsonOfField(0, "room_id", pJson["room_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("player1_uid"))
    {
        if(!validJsonOfField(1, "player1_uid", pJson["player1_uid"], err, false))
            return false;
    }
    if(pJson.isMember("player2_uid"))
    {
        if(!validJsonOfField(2, "player2_uid", pJson["player2_uid"], err, false))
            return false;
    }
    if(pJson.isMember("winner_uid"))
    {
        if(!validJsonOfField(3, "winner_uid", pJson["winner_uid"], err, false))
            return false;
    }
    if(pJson.isMember("final_score_p1"))
    {
        if(!validJsonOfField(4, "final_score_p1", pJson["final_score_p1"], err, false))
            return false;
    }
    if(pJson.isMember("final_score_p2"))
    {
        if(!validJsonOfField(5, "final_score_p2", pJson["final_score_p2"], err, false))
            return false;
    }
    if(pJson.isMember("moves"))
    {
        if(!validJsonOfField(6, "moves", pJson["moves"], err, false))
            return false;
    }
    if(pJson.isMember("played_at"))
    {
        if(!validJsonOfField(7, "played_at", pJson["played_at"], err, false))
            return false;
    }
    return true;
}
bool GameHistory::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool GameHistory::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
