/**
 *
 *  Puzzles.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Puzzles.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::neondb;

const std::string Puzzles::Cols::_puzzle_id = "\"puzzle_id\"";
const std::string Puzzles::Cols::_board_state = "\"board_state\"";
const std::string Puzzles::Cols::_rack = "\"rack\"";
const std::string Puzzles::Cols::_objective = "\"objective\"";
const std::string Puzzles::Cols::_difficulty = "\"difficulty\"";
const std::string Puzzles::Cols::_max_score = "\"max_score\"";
const std::string Puzzles::Cols::_created_at = "\"created_at\"";
const std::string Puzzles::Cols::_is_daily = "\"is_daily\"";
const std::string Puzzles::Cols::_daily_date = "\"daily_date\"";
const std::string Puzzles::primaryKeyName = "puzzle_id";
const bool Puzzles::hasPrimaryKey = true;
const std::string Puzzles::tableName = "\"puzzles\"";

const std::vector<typename Puzzles::MetaData> Puzzles::metaData_={
{"puzzle_id","int32_t","integer",4,1,1,1},
{"board_state","std::string","jsonb",0,0,0,1},
{"rack","std::string","jsonb",0,0,0,1},
{"objective","std::string","text",0,0,0,1},
{"difficulty","std::string","text",0,0,0,1},
{"max_score","int32_t","integer",4,0,0,0},
{"created_at","::trantor::Date","timestamp without time zone",0,0,0,1},
{"is_daily","bool","boolean",1,0,0,0},
{"daily_date","::trantor::Date","date",0,0,0,0}
};
const std::string &Puzzles::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Puzzles::Puzzles(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["puzzle_id"].isNull())
        {
            puzzleId_=std::make_shared<int32_t>(r["puzzle_id"].as<int32_t>());
        }
        if(!r["board_state"].isNull())
        {
            boardState_=std::make_shared<std::string>(r["board_state"].as<std::string>());
        }
        if(!r["rack"].isNull())
        {
            rack_=std::make_shared<std::string>(r["rack"].as<std::string>());
        }
        if(!r["objective"].isNull())
        {
            objective_=std::make_shared<std::string>(r["objective"].as<std::string>());
        }
        if(!r["difficulty"].isNull())
        {
            difficulty_=std::make_shared<std::string>(r["difficulty"].as<std::string>());
        }
        if(!r["max_score"].isNull())
        {
            maxScore_=std::make_shared<int32_t>(r["max_score"].as<int32_t>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["is_daily"].isNull())
        {
            isDaily_=std::make_shared<bool>(r["is_daily"].as<bool>());
        }
        if(!r["daily_date"].isNull())
        {
            auto daysStr = r["daily_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dailyDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 9 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            puzzleId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            boardState_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            rack_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            objective_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            difficulty_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            maxScore_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            isDaily_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dailyDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }

}

Puzzles::Puzzles(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            puzzleId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            boardState_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            rack_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            objective_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            difficulty_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            maxScore_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            isDaily_=std::make_shared<bool>(pJson[pMasqueradingVector[7]].asBool());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dailyDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

Puzzles::Puzzles(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("puzzle_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["puzzle_id"].isNull())
        {
            puzzleId_=std::make_shared<int32_t>((int32_t)pJson["puzzle_id"].asInt64());
        }
    }
    if(pJson.isMember("board_state"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["board_state"].isNull())
        {
            boardState_=std::make_shared<std::string>(pJson["board_state"].asString());
        }
    }
    if(pJson.isMember("rack"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["rack"].isNull())
        {
            rack_=std::make_shared<std::string>(pJson["rack"].asString());
        }
    }
    if(pJson.isMember("objective"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["objective"].isNull())
        {
            objective_=std::make_shared<std::string>(pJson["objective"].asString());
        }
    }
    if(pJson.isMember("difficulty"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["difficulty"].isNull())
        {
            difficulty_=std::make_shared<std::string>(pJson["difficulty"].asString());
        }
    }
    if(pJson.isMember("max_score"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["max_score"].isNull())
        {
            maxScore_=std::make_shared<int32_t>((int32_t)pJson["max_score"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("is_daily"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["is_daily"].isNull())
        {
            isDaily_=std::make_shared<bool>(pJson["is_daily"].asBool());
        }
    }
    if(pJson.isMember("daily_date"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["daily_date"].isNull())
        {
            auto daysStr = pJson["daily_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dailyDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

void Puzzles::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            puzzleId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            boardState_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            rack_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            objective_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            difficulty_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            maxScore_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            isDaily_=std::make_shared<bool>(pJson[pMasqueradingVector[7]].asBool());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dailyDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

void Puzzles::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("puzzle_id"))
    {
        if(!pJson["puzzle_id"].isNull())
        {
            puzzleId_=std::make_shared<int32_t>((int32_t)pJson["puzzle_id"].asInt64());
        }
    }
    if(pJson.isMember("board_state"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["board_state"].isNull())
        {
            boardState_=std::make_shared<std::string>(pJson["board_state"].asString());
        }
    }
    if(pJson.isMember("rack"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["rack"].isNull())
        {
            rack_=std::make_shared<std::string>(pJson["rack"].asString());
        }
    }
    if(pJson.isMember("objective"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["objective"].isNull())
        {
            objective_=std::make_shared<std::string>(pJson["objective"].asString());
        }
    }
    if(pJson.isMember("difficulty"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["difficulty"].isNull())
        {
            difficulty_=std::make_shared<std::string>(pJson["difficulty"].asString());
        }
    }
    if(pJson.isMember("max_score"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["max_score"].isNull())
        {
            maxScore_=std::make_shared<int32_t>((int32_t)pJson["max_score"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("is_daily"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["is_daily"].isNull())
        {
            isDaily_=std::make_shared<bool>(pJson["is_daily"].asBool());
        }
    }
    if(pJson.isMember("daily_date"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["daily_date"].isNull())
        {
            auto daysStr = pJson["daily_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dailyDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

const int32_t &Puzzles::getValueOfPuzzleId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(puzzleId_)
        return *puzzleId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Puzzles::getPuzzleId() const noexcept
{
    return puzzleId_;
}
void Puzzles::setPuzzleId(const int32_t &pPuzzleId) noexcept
{
    puzzleId_ = std::make_shared<int32_t>(pPuzzleId);
    dirtyFlag_[0] = true;
}
const typename Puzzles::PrimaryKeyType & Puzzles::getPrimaryKey() const
{
    assert(puzzleId_);
    return *puzzleId_;
}

const std::string &Puzzles::getValueOfBoardState() const noexcept
{
    static const std::string defaultValue = std::string();
    if(boardState_)
        return *boardState_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Puzzles::getBoardState() const noexcept
{
    return boardState_;
}
void Puzzles::setBoardState(const std::string &pBoardState) noexcept
{
    boardState_ = std::make_shared<std::string>(pBoardState);
    dirtyFlag_[1] = true;
}
void Puzzles::setBoardState(std::string &&pBoardState) noexcept
{
    boardState_ = std::make_shared<std::string>(std::move(pBoardState));
    dirtyFlag_[1] = true;
}

const std::string &Puzzles::getValueOfRack() const noexcept
{
    static const std::string defaultValue = std::string();
    if(rack_)
        return *rack_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Puzzles::getRack() const noexcept
{
    return rack_;
}
void Puzzles::setRack(const std::string &pRack) noexcept
{
    rack_ = std::make_shared<std::string>(pRack);
    dirtyFlag_[2] = true;
}
void Puzzles::setRack(std::string &&pRack) noexcept
{
    rack_ = std::make_shared<std::string>(std::move(pRack));
    dirtyFlag_[2] = true;
}

const std::string &Puzzles::getValueOfObjective() const noexcept
{
    static const std::string defaultValue = std::string();
    if(objective_)
        return *objective_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Puzzles::getObjective() const noexcept
{
    return objective_;
}
void Puzzles::setObjective(const std::string &pObjective) noexcept
{
    objective_ = std::make_shared<std::string>(pObjective);
    dirtyFlag_[3] = true;
}
void Puzzles::setObjective(std::string &&pObjective) noexcept
{
    objective_ = std::make_shared<std::string>(std::move(pObjective));
    dirtyFlag_[3] = true;
}

const std::string &Puzzles::getValueOfDifficulty() const noexcept
{
    static const std::string defaultValue = std::string();
    if(difficulty_)
        return *difficulty_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Puzzles::getDifficulty() const noexcept
{
    return difficulty_;
}
void Puzzles::setDifficulty(const std::string &pDifficulty) noexcept
{
    difficulty_ = std::make_shared<std::string>(pDifficulty);
    dirtyFlag_[4] = true;
}
void Puzzles::setDifficulty(std::string &&pDifficulty) noexcept
{
    difficulty_ = std::make_shared<std::string>(std::move(pDifficulty));
    dirtyFlag_[4] = true;
}

const int32_t &Puzzles::getValueOfMaxScore() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(maxScore_)
        return *maxScore_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Puzzles::getMaxScore() const noexcept
{
    return maxScore_;
}
void Puzzles::setMaxScore(const int32_t &pMaxScore) noexcept
{
    maxScore_ = std::make_shared<int32_t>(pMaxScore);
    dirtyFlag_[5] = true;
}
void Puzzles::setMaxScoreToNull() noexcept
{
    maxScore_.reset();
    dirtyFlag_[5] = true;
}

const ::trantor::Date &Puzzles::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Puzzles::getCreatedAt() const noexcept
{
    return createdAt_;
}
void Puzzles::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[6] = true;
}

const bool &Puzzles::getValueOfIsDaily() const noexcept
{
    static const bool defaultValue = bool();
    if(isDaily_)
        return *isDaily_;
    return defaultValue;
}
const std::shared_ptr<bool> &Puzzles::getIsDaily() const noexcept
{
    return isDaily_;
}
void Puzzles::setIsDaily(const bool &pIsDaily) noexcept
{
    isDaily_ = std::make_shared<bool>(pIsDaily);
    dirtyFlag_[7] = true;
}
void Puzzles::setIsDailyToNull() noexcept
{
    isDaily_.reset();
    dirtyFlag_[7] = true;
}

const ::trantor::Date &Puzzles::getValueOfDailyDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(dailyDate_)
        return *dailyDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Puzzles::getDailyDate() const noexcept
{
    return dailyDate_;
}
void Puzzles::setDailyDate(const ::trantor::Date &pDailyDate) noexcept
{
    dailyDate_ = std::make_shared<::trantor::Date>(pDailyDate.roundDay());
    dirtyFlag_[8] = true;
}
void Puzzles::setDailyDateToNull() noexcept
{
    dailyDate_.reset();
    dirtyFlag_[8] = true;
}

void Puzzles::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Puzzles::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "board_state",
        "rack",
        "objective",
        "difficulty",
        "max_score",
        "created_at",
        "is_daily",
        "daily_date"
    };
    return inCols;
}

void Puzzles::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getBoardState())
        {
            binder << getValueOfBoardState();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getRack())
        {
            binder << getValueOfRack();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getObjective())
        {
            binder << getValueOfObjective();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDifficulty())
        {
            binder << getValueOfDifficulty();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getMaxScore())
        {
            binder << getValueOfMaxScore();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getIsDaily())
        {
            binder << getValueOfIsDaily();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getDailyDate())
        {
            binder << getValueOfDailyDate();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Puzzles::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    return ret;
}

void Puzzles::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getBoardState())
        {
            binder << getValueOfBoardState();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getRack())
        {
            binder << getValueOfRack();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getObjective())
        {
            binder << getValueOfObjective();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDifficulty())
        {
            binder << getValueOfDifficulty();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getMaxScore())
        {
            binder << getValueOfMaxScore();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getIsDaily())
        {
            binder << getValueOfIsDaily();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getDailyDate())
        {
            binder << getValueOfDailyDate();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Puzzles::toJson() const
{
    Json::Value ret;
    if(getPuzzleId())
    {
        ret["puzzle_id"]=getValueOfPuzzleId();
    }
    else
    {
        ret["puzzle_id"]=Json::Value();
    }
    if(getBoardState())
    {
        ret["board_state"]=getValueOfBoardState();
    }
    else
    {
        ret["board_state"]=Json::Value();
    }
    if(getRack())
    {
        ret["rack"]=getValueOfRack();
    }
    else
    {
        ret["rack"]=Json::Value();
    }
    if(getObjective())
    {
        ret["objective"]=getValueOfObjective();
    }
    else
    {
        ret["objective"]=Json::Value();
    }
    if(getDifficulty())
    {
        ret["difficulty"]=getValueOfDifficulty();
    }
    else
    {
        ret["difficulty"]=Json::Value();
    }
    if(getMaxScore())
    {
        ret["max_score"]=getValueOfMaxScore();
    }
    else
    {
        ret["max_score"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getIsDaily())
    {
        ret["is_daily"]=getValueOfIsDaily();
    }
    else
    {
        ret["is_daily"]=Json::Value();
    }
    if(getDailyDate())
    {
        ret["daily_date"]=getDailyDate()->toDbStringLocal();
    }
    else
    {
        ret["daily_date"]=Json::Value();
    }
    return ret;
}

std::string Puzzles::toString() const
{
    return toJson().toStyledString();
}

Json::Value Puzzles::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 9)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getPuzzleId())
            {
                ret[pMasqueradingVector[0]]=getValueOfPuzzleId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getBoardState())
            {
                ret[pMasqueradingVector[1]]=getValueOfBoardState();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getRack())
            {
                ret[pMasqueradingVector[2]]=getValueOfRack();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getObjective())
            {
                ret[pMasqueradingVector[3]]=getValueOfObjective();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getDifficulty())
            {
                ret[pMasqueradingVector[4]]=getValueOfDifficulty();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getMaxScore())
            {
                ret[pMasqueradingVector[5]]=getValueOfMaxScore();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[6]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getIsDaily())
            {
                ret[pMasqueradingVector[7]]=getValueOfIsDaily();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getDailyDate())
            {
                ret[pMasqueradingVector[8]]=getDailyDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getPuzzleId())
    {
        ret["puzzle_id"]=getValueOfPuzzleId();
    }
    else
    {
        ret["puzzle_id"]=Json::Value();
    }
    if(getBoardState())
    {
        ret["board_state"]=getValueOfBoardState();
    }
    else
    {
        ret["board_state"]=Json::Value();
    }
    if(getRack())
    {
        ret["rack"]=getValueOfRack();
    }
    else
    {
        ret["rack"]=Json::Value();
    }
    if(getObjective())
    {
        ret["objective"]=getValueOfObjective();
    }
    else
    {
        ret["objective"]=Json::Value();
    }
    if(getDifficulty())
    {
        ret["difficulty"]=getValueOfDifficulty();
    }
    else
    {
        ret["difficulty"]=Json::Value();
    }
    if(getMaxScore())
    {
        ret["max_score"]=getValueOfMaxScore();
    }
    else
    {
        ret["max_score"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getIsDaily())
    {
        ret["is_daily"]=getValueOfIsDaily();
    }
    else
    {
        ret["is_daily"]=Json::Value();
    }
    if(getDailyDate())
    {
        ret["daily_date"]=getDailyDate()->toDbStringLocal();
    }
    else
    {
        ret["daily_date"]=Json::Value();
    }
    return ret;
}

bool Puzzles::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("puzzle_id"))
    {
        if(!validJsonOfField(0, "puzzle_id", pJson["puzzle_id"], err, true))
            return false;
    }
    if(pJson.isMember("board_state"))
    {
        if(!validJsonOfField(1, "board_state", pJson["board_state"], err, true))
            return false;
    }
    else
    {
        err="The board_state column cannot be null";
        return false;
    }
    if(pJson.isMember("rack"))
    {
        if(!validJsonOfField(2, "rack", pJson["rack"], err, true))
            return false;
    }
    else
    {
        err="The rack column cannot be null";
        return false;
    }
    if(pJson.isMember("objective"))
    {
        if(!validJsonOfField(3, "objective", pJson["objective"], err, true))
            return false;
    }
    else
    {
        err="The objective column cannot be null";
        return false;
    }
    if(pJson.isMember("difficulty"))
    {
        if(!validJsonOfField(4, "difficulty", pJson["difficulty"], err, true))
            return false;
    }
    else
    {
        err="The difficulty column cannot be null";
        return false;
    }
    if(pJson.isMember("max_score"))
    {
        if(!validJsonOfField(5, "max_score", pJson["max_score"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(6, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("is_daily"))
    {
        if(!validJsonOfField(7, "is_daily", pJson["is_daily"], err, true))
            return false;
    }
    if(pJson.isMember("daily_date"))
    {
        if(!validJsonOfField(8, "daily_date", pJson["daily_date"], err, true))
            return false;
    }
    return true;
}
bool Puzzles::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Puzzles::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("puzzle_id"))
    {
        if(!validJsonOfField(0, "puzzle_id", pJson["puzzle_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("board_state"))
    {
        if(!validJsonOfField(1, "board_state", pJson["board_state"], err, false))
            return false;
    }
    if(pJson.isMember("rack"))
    {
        if(!validJsonOfField(2, "rack", pJson["rack"], err, false))
            return false;
    }
    if(pJson.isMember("objective"))
    {
        if(!validJsonOfField(3, "objective", pJson["objective"], err, false))
            return false;
    }
    if(pJson.isMember("difficulty"))
    {
        if(!validJsonOfField(4, "difficulty", pJson["difficulty"], err, false))
            return false;
    }
    if(pJson.isMember("max_score"))
    {
        if(!validJsonOfField(5, "max_score", pJson["max_score"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(6, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("is_daily"))
    {
        if(!validJsonOfField(7, "is_daily", pJson["is_daily"], err, false))
            return false;
    }
    if(pJson.isMember("daily_date"))
    {
        if(!validJsonOfField(8, "daily_date", pJson["daily_date"], err, false))
            return false;
    }
    return true;
}
bool Puzzles::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Puzzles::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
