/**
 *
 *  PuzzleProgress.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "PuzzleProgress.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::neondb;

const std::string PuzzleProgress::Cols::_id = "\"id\"";
const std::string PuzzleProgress::Cols::_user_id = "\"user_id\"";
const std::string PuzzleProgress::Cols::_puzzle_id = "\"puzzle_id\"";
const std::string PuzzleProgress::Cols::_solved = "\"solved\"";
const std::string PuzzleProgress::Cols::_last_updated = "\"last_updated\"";
const std::string PuzzleProgress::Cols::_attempts = "\"attempts\"";
const std::string PuzzleProgress::Cols::_best_time = "\"best_time\"";
const std::string PuzzleProgress::Cols::_best_score = "\"best_score\"";
const std::string PuzzleProgress::Cols::_first_completed_at = "\"first_completed_at\"";
const std::string PuzzleProgress::Cols::_last_attempted_at = "\"last_attempted_at\"";
const std::string PuzzleProgress::primaryKeyName = "id";
const bool PuzzleProgress::hasPrimaryKey = true;
const std::string PuzzleProgress::tableName = "\"puzzle_progress\"";

const std::vector<typename PuzzleProgress::MetaData> PuzzleProgress::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"user_id","std::string","character varying",255,0,0,1},
{"puzzle_id","int32_t","integer",4,0,0,1},
{"solved","bool","boolean",1,0,0,0},
{"last_updated","::trantor::Date","timestamp without time zone",0,0,0,0},
{"attempts","int32_t","integer",4,0,0,0},
{"best_time","int32_t","integer",4,0,0,0},
{"best_score","int32_t","integer",4,0,0,0},
{"first_completed_at","::trantor::Date","timestamp without time zone",0,0,0,0},
{"last_attempted_at","::trantor::Date","timestamp without time zone",0,0,0,0}
};
const std::string &PuzzleProgress::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
PuzzleProgress::PuzzleProgress(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(r["user_id"].as<std::string>());
        }
        if(!r["puzzle_id"].isNull())
        {
            puzzleId_=std::make_shared<int32_t>(r["puzzle_id"].as<int32_t>());
        }
        if(!r["solved"].isNull())
        {
            solved_=std::make_shared<bool>(r["solved"].as<bool>());
        }
        if(!r["last_updated"].isNull())
        {
            auto timeStr = r["last_updated"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["attempts"].isNull())
        {
            attempts_=std::make_shared<int32_t>(r["attempts"].as<int32_t>());
        }
        if(!r["best_time"].isNull())
        {
            bestTime_=std::make_shared<int32_t>(r["best_time"].as<int32_t>());
        }
        if(!r["best_score"].isNull())
        {
            bestScore_=std::make_shared<int32_t>(r["best_score"].as<int32_t>());
        }
        if(!r["first_completed_at"].isNull())
        {
            auto timeStr = r["first_completed_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                firstCompletedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["last_attempted_at"].isNull())
        {
            auto timeStr = r["last_attempted_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastAttemptedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 10 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            puzzleId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            solved_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            attempts_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            bestTime_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            bestScore_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                firstCompletedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastAttemptedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

PuzzleProgress::PuzzleProgress(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            puzzleId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            solved_=std::make_shared<bool>(pJson[pMasqueradingVector[3]].asBool());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            attempts_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            bestTime_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            bestScore_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                firstCompletedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastAttemptedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

PuzzleProgress::PuzzleProgress(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("puzzle_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["puzzle_id"].isNull())
        {
            puzzleId_=std::make_shared<int32_t>((int32_t)pJson["puzzle_id"].asInt64());
        }
    }
    if(pJson.isMember("solved"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["solved"].isNull())
        {
            solved_=std::make_shared<bool>(pJson["solved"].asBool());
        }
    }
    if(pJson.isMember("last_updated"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["last_updated"].isNull())
        {
            auto timeStr = pJson["last_updated"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("attempts"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["attempts"].isNull())
        {
            attempts_=std::make_shared<int32_t>((int32_t)pJson["attempts"].asInt64());
        }
    }
    if(pJson.isMember("best_time"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["best_time"].isNull())
        {
            bestTime_=std::make_shared<int32_t>((int32_t)pJson["best_time"].asInt64());
        }
    }
    if(pJson.isMember("best_score"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["best_score"].isNull())
        {
            bestScore_=std::make_shared<int32_t>((int32_t)pJson["best_score"].asInt64());
        }
    }
    if(pJson.isMember("first_completed_at"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["first_completed_at"].isNull())
        {
            auto timeStr = pJson["first_completed_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                firstCompletedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("last_attempted_at"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["last_attempted_at"].isNull())
        {
            auto timeStr = pJson["last_attempted_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastAttemptedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void PuzzleProgress::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            puzzleId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            solved_=std::make_shared<bool>(pJson[pMasqueradingVector[3]].asBool());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            attempts_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            bestTime_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            bestScore_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                firstCompletedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastAttemptedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void PuzzleProgress::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("puzzle_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["puzzle_id"].isNull())
        {
            puzzleId_=std::make_shared<int32_t>((int32_t)pJson["puzzle_id"].asInt64());
        }
    }
    if(pJson.isMember("solved"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["solved"].isNull())
        {
            solved_=std::make_shared<bool>(pJson["solved"].asBool());
        }
    }
    if(pJson.isMember("last_updated"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["last_updated"].isNull())
        {
            auto timeStr = pJson["last_updated"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("attempts"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["attempts"].isNull())
        {
            attempts_=std::make_shared<int32_t>((int32_t)pJson["attempts"].asInt64());
        }
    }
    if(pJson.isMember("best_time"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["best_time"].isNull())
        {
            bestTime_=std::make_shared<int32_t>((int32_t)pJson["best_time"].asInt64());
        }
    }
    if(pJson.isMember("best_score"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["best_score"].isNull())
        {
            bestScore_=std::make_shared<int32_t>((int32_t)pJson["best_score"].asInt64());
        }
    }
    if(pJson.isMember("first_completed_at"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["first_completed_at"].isNull())
        {
            auto timeStr = pJson["first_completed_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                firstCompletedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("last_attempted_at"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["last_attempted_at"].isNull())
        {
            auto timeStr = pJson["last_attempted_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastAttemptedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int32_t &PuzzleProgress::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PuzzleProgress::getId() const noexcept
{
    return id_;
}
void PuzzleProgress::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename PuzzleProgress::PrimaryKeyType & PuzzleProgress::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &PuzzleProgress::getValueOfUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PuzzleProgress::getUserId() const noexcept
{
    return userId_;
}
void PuzzleProgress::setUserId(const std::string &pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(pUserId);
    dirtyFlag_[1] = true;
}
void PuzzleProgress::setUserId(std::string &&pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(std::move(pUserId));
    dirtyFlag_[1] = true;
}

const int32_t &PuzzleProgress::getValueOfPuzzleId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(puzzleId_)
        return *puzzleId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PuzzleProgress::getPuzzleId() const noexcept
{
    return puzzleId_;
}
void PuzzleProgress::setPuzzleId(const int32_t &pPuzzleId) noexcept
{
    puzzleId_ = std::make_shared<int32_t>(pPuzzleId);
    dirtyFlag_[2] = true;
}

const bool &PuzzleProgress::getValueOfSolved() const noexcept
{
    static const bool defaultValue = bool();
    if(solved_)
        return *solved_;
    return defaultValue;
}
const std::shared_ptr<bool> &PuzzleProgress::getSolved() const noexcept
{
    return solved_;
}
void PuzzleProgress::setSolved(const bool &pSolved) noexcept
{
    solved_ = std::make_shared<bool>(pSolved);
    dirtyFlag_[3] = true;
}
void PuzzleProgress::setSolvedToNull() noexcept
{
    solved_.reset();
    dirtyFlag_[3] = true;
}

const ::trantor::Date &PuzzleProgress::getValueOfLastUpdated() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(lastUpdated_)
        return *lastUpdated_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PuzzleProgress::getLastUpdated() const noexcept
{
    return lastUpdated_;
}
void PuzzleProgress::setLastUpdated(const ::trantor::Date &pLastUpdated) noexcept
{
    lastUpdated_ = std::make_shared<::trantor::Date>(pLastUpdated);
    dirtyFlag_[4] = true;
}
void PuzzleProgress::setLastUpdatedToNull() noexcept
{
    lastUpdated_.reset();
    dirtyFlag_[4] = true;
}

const int32_t &PuzzleProgress::getValueOfAttempts() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(attempts_)
        return *attempts_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PuzzleProgress::getAttempts() const noexcept
{
    return attempts_;
}
void PuzzleProgress::setAttempts(const int32_t &pAttempts) noexcept
{
    attempts_ = std::make_shared<int32_t>(pAttempts);
    dirtyFlag_[5] = true;
}
void PuzzleProgress::setAttemptsToNull() noexcept
{
    attempts_.reset();
    dirtyFlag_[5] = true;
}

const int32_t &PuzzleProgress::getValueOfBestTime() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(bestTime_)
        return *bestTime_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PuzzleProgress::getBestTime() const noexcept
{
    return bestTime_;
}
void PuzzleProgress::setBestTime(const int32_t &pBestTime) noexcept
{
    bestTime_ = std::make_shared<int32_t>(pBestTime);
    dirtyFlag_[6] = true;
}
void PuzzleProgress::setBestTimeToNull() noexcept
{
    bestTime_.reset();
    dirtyFlag_[6] = true;
}

const int32_t &PuzzleProgress::getValueOfBestScore() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(bestScore_)
        return *bestScore_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PuzzleProgress::getBestScore() const noexcept
{
    return bestScore_;
}
void PuzzleProgress::setBestScore(const int32_t &pBestScore) noexcept
{
    bestScore_ = std::make_shared<int32_t>(pBestScore);
    dirtyFlag_[7] = true;
}
void PuzzleProgress::setBestScoreToNull() noexcept
{
    bestScore_.reset();
    dirtyFlag_[7] = true;
}

const ::trantor::Date &PuzzleProgress::getValueOfFirstCompletedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(firstCompletedAt_)
        return *firstCompletedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PuzzleProgress::getFirstCompletedAt() const noexcept
{
    return firstCompletedAt_;
}
void PuzzleProgress::setFirstCompletedAt(const ::trantor::Date &pFirstCompletedAt) noexcept
{
    firstCompletedAt_ = std::make_shared<::trantor::Date>(pFirstCompletedAt);
    dirtyFlag_[8] = true;
}
void PuzzleProgress::setFirstCompletedAtToNull() noexcept
{
    firstCompletedAt_.reset();
    dirtyFlag_[8] = true;
}

const ::trantor::Date &PuzzleProgress::getValueOfLastAttemptedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(lastAttemptedAt_)
        return *lastAttemptedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PuzzleProgress::getLastAttemptedAt() const noexcept
{
    return lastAttemptedAt_;
}
void PuzzleProgress::setLastAttemptedAt(const ::trantor::Date &pLastAttemptedAt) noexcept
{
    lastAttemptedAt_ = std::make_shared<::trantor::Date>(pLastAttemptedAt);
    dirtyFlag_[9] = true;
}
void PuzzleProgress::setLastAttemptedAtToNull() noexcept
{
    lastAttemptedAt_.reset();
    dirtyFlag_[9] = true;
}

void PuzzleProgress::updateId(const uint64_t id)
{
}

const std::vector<std::string> &PuzzleProgress::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "user_id",
        "puzzle_id",
        "solved",
        "last_updated",
        "attempts",
        "best_time",
        "best_score",
        "first_completed_at",
        "last_attempted_at"
    };
    return inCols;
}

void PuzzleProgress::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPuzzleId())
        {
            binder << getValueOfPuzzleId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSolved())
        {
            binder << getValueOfSolved();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getLastUpdated())
        {
            binder << getValueOfLastUpdated();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAttempts())
        {
            binder << getValueOfAttempts();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getBestTime())
        {
            binder << getValueOfBestTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getBestScore())
        {
            binder << getValueOfBestScore();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getFirstCompletedAt())
        {
            binder << getValueOfFirstCompletedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getLastAttemptedAt())
        {
            binder << getValueOfLastAttemptedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> PuzzleProgress::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    return ret;
}

void PuzzleProgress::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPuzzleId())
        {
            binder << getValueOfPuzzleId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSolved())
        {
            binder << getValueOfSolved();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getLastUpdated())
        {
            binder << getValueOfLastUpdated();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAttempts())
        {
            binder << getValueOfAttempts();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getBestTime())
        {
            binder << getValueOfBestTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getBestScore())
        {
            binder << getValueOfBestScore();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getFirstCompletedAt())
        {
            binder << getValueOfFirstCompletedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getLastAttemptedAt())
        {
            binder << getValueOfLastAttemptedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value PuzzleProgress::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getPuzzleId())
    {
        ret["puzzle_id"]=getValueOfPuzzleId();
    }
    else
    {
        ret["puzzle_id"]=Json::Value();
    }
    if(getSolved())
    {
        ret["solved"]=getValueOfSolved();
    }
    else
    {
        ret["solved"]=Json::Value();
    }
    if(getLastUpdated())
    {
        ret["last_updated"]=getLastUpdated()->toDbStringLocal();
    }
    else
    {
        ret["last_updated"]=Json::Value();
    }
    if(getAttempts())
    {
        ret["attempts"]=getValueOfAttempts();
    }
    else
    {
        ret["attempts"]=Json::Value();
    }
    if(getBestTime())
    {
        ret["best_time"]=getValueOfBestTime();
    }
    else
    {
        ret["best_time"]=Json::Value();
    }
    if(getBestScore())
    {
        ret["best_score"]=getValueOfBestScore();
    }
    else
    {
        ret["best_score"]=Json::Value();
    }
    if(getFirstCompletedAt())
    {
        ret["first_completed_at"]=getFirstCompletedAt()->toDbStringLocal();
    }
    else
    {
        ret["first_completed_at"]=Json::Value();
    }
    if(getLastAttemptedAt())
    {
        ret["last_attempted_at"]=getLastAttemptedAt()->toDbStringLocal();
    }
    else
    {
        ret["last_attempted_at"]=Json::Value();
    }
    return ret;
}

std::string PuzzleProgress::toString() const
{
    return toJson().toStyledString();
}

Json::Value PuzzleProgress::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 10)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[1]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPuzzleId())
            {
                ret[pMasqueradingVector[2]]=getValueOfPuzzleId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getSolved())
            {
                ret[pMasqueradingVector[3]]=getValueOfSolved();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getLastUpdated())
            {
                ret[pMasqueradingVector[4]]=getLastUpdated()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getAttempts())
            {
                ret[pMasqueradingVector[5]]=getValueOfAttempts();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getBestTime())
            {
                ret[pMasqueradingVector[6]]=getValueOfBestTime();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getBestScore())
            {
                ret[pMasqueradingVector[7]]=getValueOfBestScore();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getFirstCompletedAt())
            {
                ret[pMasqueradingVector[8]]=getFirstCompletedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getLastAttemptedAt())
            {
                ret[pMasqueradingVector[9]]=getLastAttemptedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getPuzzleId())
    {
        ret["puzzle_id"]=getValueOfPuzzleId();
    }
    else
    {
        ret["puzzle_id"]=Json::Value();
    }
    if(getSolved())
    {
        ret["solved"]=getValueOfSolved();
    }
    else
    {
        ret["solved"]=Json::Value();
    }
    if(getLastUpdated())
    {
        ret["last_updated"]=getLastUpdated()->toDbStringLocal();
    }
    else
    {
        ret["last_updated"]=Json::Value();
    }
    if(getAttempts())
    {
        ret["attempts"]=getValueOfAttempts();
    }
    else
    {
        ret["attempts"]=Json::Value();
    }
    if(getBestTime())
    {
        ret["best_time"]=getValueOfBestTime();
    }
    else
    {
        ret["best_time"]=Json::Value();
    }
    if(getBestScore())
    {
        ret["best_score"]=getValueOfBestScore();
    }
    else
    {
        ret["best_score"]=Json::Value();
    }
    if(getFirstCompletedAt())
    {
        ret["first_completed_at"]=getFirstCompletedAt()->toDbStringLocal();
    }
    else
    {
        ret["first_completed_at"]=Json::Value();
    }
    if(getLastAttemptedAt())
    {
        ret["last_attempted_at"]=getLastAttemptedAt()->toDbStringLocal();
    }
    else
    {
        ret["last_attempted_at"]=Json::Value();
    }
    return ret;
}

bool PuzzleProgress::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("puzzle_id"))
    {
        if(!validJsonOfField(2, "puzzle_id", pJson["puzzle_id"], err, true))
            return false;
    }
    else
    {
        err="The puzzle_id column cannot be null";
        return false;
    }
    if(pJson.isMember("solved"))
    {
        if(!validJsonOfField(3, "solved", pJson["solved"], err, true))
            return false;
    }
    if(pJson.isMember("last_updated"))
    {
        if(!validJsonOfField(4, "last_updated", pJson["last_updated"], err, true))
            return false;
    }
    if(pJson.isMember("attempts"))
    {
        if(!validJsonOfField(5, "attempts", pJson["attempts"], err, true))
            return false;
    }
    if(pJson.isMember("best_time"))
    {
        if(!validJsonOfField(6, "best_time", pJson["best_time"], err, true))
            return false;
    }
    if(pJson.isMember("best_score"))
    {
        if(!validJsonOfField(7, "best_score", pJson["best_score"], err, true))
            return false;
    }
    if(pJson.isMember("first_completed_at"))
    {
        if(!validJsonOfField(8, "first_completed_at", pJson["first_completed_at"], err, true))
            return false;
    }
    if(pJson.isMember("last_attempted_at"))
    {
        if(!validJsonOfField(9, "last_attempted_at", pJson["last_attempted_at"], err, true))
            return false;
    }
    return true;
}
bool PuzzleProgress::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PuzzleProgress::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("puzzle_id"))
    {
        if(!validJsonOfField(2, "puzzle_id", pJson["puzzle_id"], err, false))
            return false;
    }
    if(pJson.isMember("solved"))
    {
        if(!validJsonOfField(3, "solved", pJson["solved"], err, false))
            return false;
    }
    if(pJson.isMember("last_updated"))
    {
        if(!validJsonOfField(4, "last_updated", pJson["last_updated"], err, false))
            return false;
    }
    if(pJson.isMember("attempts"))
    {
        if(!validJsonOfField(5, "attempts", pJson["attempts"], err, false))
            return false;
    }
    if(pJson.isMember("best_time"))
    {
        if(!validJsonOfField(6, "best_time", pJson["best_time"], err, false))
            return false;
    }
    if(pJson.isMember("best_score"))
    {
        if(!validJsonOfField(7, "best_score", pJson["best_score"], err, false))
            return false;
    }
    if(pJson.isMember("first_completed_at"))
    {
        if(!validJsonOfField(8, "first_completed_at", pJson["first_completed_at"], err, false))
            return false;
    }
    if(pJson.isMember("last_attempted_at"))
    {
        if(!validJsonOfField(9, "last_attempted_at", pJson["last_attempted_at"], err, false))
            return false;
    }
    return true;
}
bool PuzzleProgress::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PuzzleProgress::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
