/**
 *
 *  Puzzles.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace neondb
{

class Puzzles
{
  public:
    struct Cols
    {
        static const std::string _puzzle_id;
        static const std::string _board_state;
        static const std::string _rack;
        static const std::string _objective;
        static const std::string _difficulty;
        static const std::string _max_score;
        static const std::string _created_at;
        static const std::string _is_daily;
        static const std::string _daily_date;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Puzzles(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Puzzles(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Puzzles(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Puzzles() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column puzzle_id  */
    ///Get the value of the column puzzle_id, returns the default value if the column is null
    const int32_t &getValueOfPuzzleId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getPuzzleId() const noexcept;
    ///Set the value of the column puzzle_id
    void setPuzzleId(const int32_t &pPuzzleId) noexcept;

    /**  For column board_state  */
    ///Get the value of the column board_state, returns the default value if the column is null
    const std::string &getValueOfBoardState() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBoardState() const noexcept;
    ///Set the value of the column board_state
    void setBoardState(const std::string &pBoardState) noexcept;
    void setBoardState(std::string &&pBoardState) noexcept;

    /**  For column rack  */
    ///Get the value of the column rack, returns the default value if the column is null
    const std::string &getValueOfRack() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRack() const noexcept;
    ///Set the value of the column rack
    void setRack(const std::string &pRack) noexcept;
    void setRack(std::string &&pRack) noexcept;

    /**  For column objective  */
    ///Get the value of the column objective, returns the default value if the column is null
    const std::string &getValueOfObjective() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getObjective() const noexcept;
    ///Set the value of the column objective
    void setObjective(const std::string &pObjective) noexcept;
    void setObjective(std::string &&pObjective) noexcept;

    /**  For column difficulty  */
    ///Get the value of the column difficulty, returns the default value if the column is null
    const std::string &getValueOfDifficulty() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDifficulty() const noexcept;
    ///Set the value of the column difficulty
    void setDifficulty(const std::string &pDifficulty) noexcept;
    void setDifficulty(std::string &&pDifficulty) noexcept;

    /**  For column max_score  */
    ///Get the value of the column max_score, returns the default value if the column is null
    const int32_t &getValueOfMaxScore() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getMaxScore() const noexcept;
    ///Set the value of the column max_score
    void setMaxScore(const int32_t &pMaxScore) noexcept;
    void setMaxScoreToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;

    /**  For column is_daily  */
    ///Get the value of the column is_daily, returns the default value if the column is null
    const bool &getValueOfIsDaily() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsDaily() const noexcept;
    ///Set the value of the column is_daily
    void setIsDaily(const bool &pIsDaily) noexcept;
    void setIsDailyToNull() noexcept;

    /**  For column daily_date  */
    ///Get the value of the column daily_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfDailyDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getDailyDate() const noexcept;
    ///Set the value of the column daily_date
    void setDailyDate(const ::trantor::Date &pDailyDate) noexcept;
    void setDailyDateToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 9;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Puzzles>;
    friend drogon::orm::BaseBuilder<Puzzles, true, true>;
    friend drogon::orm::BaseBuilder<Puzzles, true, false>;
    friend drogon::orm::BaseBuilder<Puzzles, false, true>;
    friend drogon::orm::BaseBuilder<Puzzles, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Puzzles>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> puzzleId_;
    std::shared_ptr<std::string> boardState_;
    std::shared_ptr<std::string> rack_;
    std::shared_ptr<std::string> objective_;
    std::shared_ptr<std::string> difficulty_;
    std::shared_ptr<int32_t> maxScore_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<bool> isDaily_;
    std::shared_ptr<::trantor::Date> dailyDate_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[9]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where puzzle_id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where puzzle_id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "puzzle_id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "board_state,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "rack,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "objective,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "difficulty,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "max_score,";
            ++parametersCount;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[6])
        {
            needSelection=true;
        }
        sql += "is_daily,";
        ++parametersCount;
        if(!dirtyFlag_[7])
        {
            needSelection=true;
        }
        if(dirtyFlag_[8])
        {
            sql += "daily_date,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace neondb
} // namespace drogon_model
